[package]
name = "device_faker_cli"
version = "0.1.0"
edition = "2024"
authors = ["Seyud"]

[dependencies]
anyhow.workspace = true
argh = "0.1"
minreq = { version = "2.11", default-features = false, features = ["https-rustls", "json-using-serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
toml.workspace = true

[[bin]]
name = "device_faker_cli"
path = "src/main.rs"
