name: Build Device Faker Module

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - "Cargo.*"
      - 'device_faker_cli/**'
      - 'module/**'
      - 'webui/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - "Cargo.*"
      - 'device_faker_cli/**'
      - 'module/**'
      - 'webui/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29
          add-to-path: true

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src
          toolchain: nightly
          targets: aarch64-linux-android
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: webui/package-lock.json
          
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib
          cargo install cargo-ndk --locked

      - name: Build device_faker
        run: |
          cargo run --package xtask -- build -r

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: device_faker
          path: module/
      
      - name: Upload
        if: github.event_name == 'push'
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
          COMMIT_MESSAGE: |+
            üöÄ **Device_Faker Build \#${{ github.run_number }}**
            üìã **Build Info:**
            [Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            üìù **Commit Message:**
            ```
            ${{ format('{0}', github.event.head_commit.message) }}
            ```
            by `${{ github.event.head_commit.author.name }}`
            
            üîó [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          ESCAPED_MESSAGE=$(echo "${COMMIT_MESSAGE}" | jq -R -s '.')
          
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup" \
               -F "chat_id=${CHAT_ID}" \
               -F "message_thread_id=${MESSAGE_THREAD_ID}" \
               -F "media=[{\"type\":\"document\",\"media\":\"attach://file\",\"parse_mode\":\"MarkdownV2\",\"caption\":${ESCAPED_MESSAGE}}]" \
               -F "file=@output/device_faker-(release).zip"
